In [4]:
import numpy as np

In [5]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
list(range(0, 10, 3))

[0, 3, 6, 9]

In [23]:
x = np.array([[0.1, 0.2, 0.1], [0.3, 0.1, 0.4], [0.2, 0.5,0.3], [0.4, 0.1, 0.1]])
print(x)

y = np.argmax(x, axis=1)
print(y)

[[0.1 0.2 0.1]
 [0.3 0.1 0.4]
 [0.2 0.5 0.3]
 [0.4 0.1 0.1]]
[1 2 1 0]


In [26]:
def sum_squares_error(y, t):
    return 0.5 * np.sum((y - t) ** 2)


In [28]:
t = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]

y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0]

sum_squares_error(np.array(y), np.array(t))

np.float64(0.09750000000000003)

In [29]:
t = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]

y = [0.1, 0.05, 0.1, 0.0, 0.05, 0.1, 0.0, 0.6, 0.0, 0.0]

sum_squares_error(np.array(y), np.array(t))

np.float64(0.5975)

In [31]:
def cross_entropy_error(y, t):
    delta = 1e-7
    return -np.sum(t * np.log(y + delta))

In [32]:
t = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0]

cross_entropy_error(np.array(y), np.array(t))

np.float64(0.510825457099338)